// ============================================================================
// Operator brain selection. Swap implementations via OPERATOR_BRAIN env:
//   fixture (default) → deterministic, reliable for the demo video
//   hermes | llm      → live operator backed by the local `hermes` CLI
//                       (see llmBrain.ts; policy-bound, falls back to fixture)
// The rest of the app only knows the OperatorBrain interface.
// ============================================================================

import type { OperatorBrain } from "@/lib/types";
import { FixtureBrain } from "@/lib/operator/fixtureBrain";

let cached: OperatorBrain | null = null;

export function getOperator(): OperatorBrain {
  if (cached) return cached;
  const mode = (process.env.OPERATOR_BRAIN ?? "fixture").toLowerCase();
  switch (mode) {
    case "llm":
    case "hermes": {
      // Loaded lazily so the default fixture path never pulls in the CLI
      // bridge / node:child_process. HermesBrain extends FixtureBrain, so all
      // policy-bound decisions stay deterministic; only buyer-facing prose is
      // generated by Hermes, with fallback to fixture text on any failure.
      const { HermesBrain } = require("@/lib/operator/llmBrain") as typeof import("@/lib/operator/llmBrain");
      cached = new HermesBrain();
      break;
    }
    case "fixture":
    default:
      cached = new FixtureBrain();
  }
  return cached;
}
